site:
  title: jMonkeyEngine Documentation
  start_page: jme::documentation.adoc 
  url: https://8keep.github.io/wikidemo-antora
content:
  sources: 
  - url: ./
    start_path: docs
    braches: HEAD
ui: 
  bundle:
    url: ./uibundle/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
output:
  clean: true
  dir: ./public
runtime:
  cache_dir: ./.cache/antora
asciidoc:
  extensions:
  - asciidoctor-emoji
